spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-3-234-204-26.compute-1.amazonaws.com/datsvlh0gtnlj9
  username: amhquhqxwjsfql
  password: 56efd01589a8446e9f45924d4bf6b8bb9c3e98711227dd8f071c4a752930b95f
  platform: postgres
  driver-class-name: org.postgresql.Driver

spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true


jwt:
  secret-key: fast-campus.simple_sns_2022_secret_key
  # 30 days
  token.expired-time-ms: 2592000000
